Fix compilation error caused by missing libftdi define
'fast.o' target cannot be compiled when compiling with libftdi1:
In file included from fast.c:10:0:
mpsse.h:10:18: fatal error: ftdi.h: No such file or directory

It is due to missing define in Makefile. Solve it by putting the
LIBFTDI1 flag directly to CFLAGS.

Signed-off-by: Tomas Novotny <tomas@novotny.cz>